# Generated by Django 3.0.6 on 2020-05-26 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_apireturnlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PnrConfirmedList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr_id', models.CharField(max_length=10)),
                ('pnr_user_id', models.CharField(max_length=10)),
                ('pnr_hotel_name', models.CharField(max_length=100)),
                ('pnr_destination_code', models.CharField(max_length=3)),
                ('pnr_email_id', models.EmailField(max_length=100)),
                ('pmr_amount', models.FloatField()),
                ('pnr_booked_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='ApiSearchList',
        ),
    ]
