# Generated by Django 3.0.6 on 2020-05-26 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_auto_20200525_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pnrconfirmedlist',
            old_name='pmr_amount',
            new_name='pnr_amount',
        ),
    ]
