# Generated by Django 3.0.6 on 2020-05-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_auto_20200525_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnrconfirmedlist',
            name='pnr_curr',
            field=models.CharField(default='AUD', max_length=3),
        ),
    ]
