# Generated by Django 3.0.6 on 2020-05-26 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_pnrconfirmedlist_pnr_curr'),
    ]

    operations = [
        migrations.AddField(
            model_name='apireturnlist',
            name='hotel_pic',
            field=models.CharField(default='room1.jpg', max_length=50),
        ),
        migrations.AlterField(
            model_name='pnrconfirmedlist',
            name='pnr_curr',
            field=models.CharField(max_length=3),
        ),
    ]
