# Generated by Django 3.0.6 on 2020-05-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_auto_20200525_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnrconfirmedlist',
            name='pnr_pic',
            field=models.CharField(default='rooms/room1.jpg', max_length=50),
        ),
    ]
